### ISSUE TITLE
bug: Only iterate over directories

### ISSUE THREAD

**Issue by bitplane** [voice-cloning-app/Voice-Cloning-App#189]
zipping up hifigan via the command line, ended up with this:

```
Type: NotADirectoryError
Text: [Errno 20] Not a directory: '/app/data/hifigan_training/vocoder.tgz'
Full: Traceback (most recent call last): File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/app/application/views.py", line 287, in get_synthesis_setup hifigan_custom_models=get_hifigan_checkpoints(), File "/app/application/views.py", line 86, in get_hifigan_checkpoints for model in os.listdir(paths["hifigan_training"]) File "/app/application/views.py", line 87, in <dictcomp> if os.listdir(os.path.join(paths["hifigan_training"], model)) NotADirectoryError: [Errno 20] Not a directory: '/app/data/hifigan_training/vocoder.tgz' 
```

**Comment by bitplane** [comment]
Same in models dir:

https://github.com/voice-cloning-app/Voice-Cloning-App/issues/183
